server:
  port: 9999

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300 # es的连接地址及端口号
      cluster-name: elasticsearch # es集群的名称
  datasource:
    url: jdbc:mysql://localhost:3307/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: banyuan
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

redis:
  key:
    prefix:
      telAuth: "telAuth:"

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  secret: ddadfasdgherw
  expiration: 5184000
  tokenHeader: Authorization
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
        - /swagger-ui.html
        - /swagger-resources/**
        - /swagger/**
        - /**/v2/api-docs
        - /**/*.js
        - /**/*.css
        - /**/*.png
        - /**/*.ico
        - /webjars/springfox-swagger-ui/css/typography.css
        - /actuator/**
        - /druid/**
        - /admin/login
        - /admin/register
        - /admin/info
        - /admin/logout
        - /minio/upload